# FROM node:latest as build-stage
# COPY package*.json ./
# RUN npm install
# COPY ./ .
# RUN npm run build

FROM nginx as production-stage
WORKDIR /site-front
RUN mkdir /site-front
COPY --from=build-stage /site-front/dist /site-front
COPY nginx.conf /etc/nginx/nginx.conf